apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveysystem
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: surveysystem-backend
  template:
    metadata:
      labels:
        app: surveysystem-backend
    spec:
      containers:
      - image: yang9501/surveysystem:42
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 8080
          name: loadbalancer
          protocol: TCP
